app/models/post.py
from datetime import datetime
from app import db
from utils import log


class Post(db.Model):
    __tablename__ = 'post'

    id = db.Column(db.Integer, primary_key=True)
    views = db.Column(db.Integer, default=0)
    title = db.Column(db.String(64))
    content = db.Column(db.Text)
    # 主页图
    image_url = db.Column(db.String(64))
    ct = db.Column(db.DateTime, default=datetime.utcnow)
    ut = db.Column(db.DateTime)

    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'))
    board_id = db.Column(db.Integer, db.ForeignKey('board.id', ondelete='CASCADE'))

    def __init__(self, form):
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.board_id = form.get('board_id', 1)
        self.image_url = form.get('image_url', '')
        self.ct = form.get('ct', datetime.utcnow())
        self.ut = self.ct

    def click(self):
        self.views += 1
        try:
            db.session.commit()
        except Exception as e:
            log(e)
        return

    def comments(self):
        from .comment import Comment
        comments = Comment.query.filter_by(post_id=self.id).all()
        return comments

app/routes/comment.py
from flask import (
    request,
    redirect,
    url_for,
    Blueprint,
    flash)

from app import db
from app.routes import *

from app.models.comment import Comment

main = Blueprint('comment', __name__)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    if u is None:
        flash('需要进行登陆', 'info')
        return redirect(url_for('index.login'))
    comment = Comment(form)
    comment.user_id = u.id
    db.session.add(comment)
    db.session.commit()
    flash('评论成功', 'success')
    return redirect(url_for('post.detail', id=comment.post_id))

app/routes/post.py
import time
from random import randint

from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    flash)

from app import db
from app.routes import *

from app.models.post import Post
from app.models.board import Board
from utils import log

main = Blueprint('post', __name__)

import uuid

csrf_tokens = dict()


@main.route("/")
def index():
    board_name = request.args.get('board_name', '')
    page = request.args.get('page', 1, type=int)
    per_page = 20
    if board_name == '':
        pagination = Post.query.order_by(Post.id.desc()).paginate(page, per_page=per_page)
    else:
        b = Board.query.filter_by(title=board_name).first()
        pagination = Post.query.filter_by(board_id=b.id).order_by(Post.id.desc()).paginate(page, per_page=per_page)
    posts = pagination.items

    token = str(uuid.uuid4())
    # 防csrf
    u = current_user()
    if u is not None:
        csrf_tokens[token] = u.id
    bs = Board.query.all()
    return render_template("post/post_index.html", posts=posts, pagination=pagination, token=token, bs=bs,
                           board_name=board_name, user=u)


@main.route('/<int:id>')
def detail(id):
    u = current_user()
    post = Post.query.filter_by(id=id).first()
    if post is None:
        flash('文章不存在', 'warning')
        return redirect('/')
    post.click()
    board = Board.query.filter_by(id=post.board_id).first()
    author = User.query.filter_by(id=post.user_id).first()
    date = post.ct
    return render_template("post/detail.html", post=post, board=board, author=author, date=date, current_user=u)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    if u is None:
        flash('需要进行登陆', 'info')
        return redirect(url_for('index.login'))
    post = Post(form)
    post.user_id = u.id
    db.session.add(post)
    db.session.commit()
    flash('提交成功', 'success')
    return redirect(url_for('.detail', id=post.id))


@main.route("/delete")
def delete():
    id = int(request.args.get('id'))
    token = request.args.get('token')
    post = Post.query.filter_by(id=id).first()
    u = current_user()
    # 判断 token
    if token in csrf_tokens and csrf_tokens[token] == u.id and (post.user_id == u.id or u.id == 1):
        Post.query.filter_by(id=id).delete()
        db.session.commit()
        flash('删除成功', 'success')
        return redirect(url_for('.index'))
    else:
        flash('没有权限进行该操作', 'warning')
        return redirect('/')


@main.route("/new")
def new():
    u = current_user()
    if u is None:
        flash('需要进行登陆', 'info')
        return redirect(url_for('index.login'))
    bs = Board.query.all()
    return render_template("post/create.html", bs=bs)


@main.route("/random")
def post_random():
    num = randint(1, Post.query.count())
    return redirect(url_for('.detail', id=num))

app/templates/post/create.html
{% extends "base.html" %}
{% block content %}

<form id="create-post-form" method="post" action="{{ url_for('.add') }}">
    <fieldset>
        <input autofocus class='form-control' name='title' placeholder="标题字数 10 字以上" required></input>

        <div class="create-post-board">
            <span class="tab-selector">选择版块：</span>
            <select id="board_id" name="board_id" class="selectpicker" required>
                <option value="">请选择</option>
                {% for b in bs %}
                <option value="{{ b.id }}">{{ b.name }}</option>
                {% endfor %}
            </select>
            <span class="board-msg"></span>
        </div>
                <textarea id="create-post-content" class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                <span class="content-msg"></span>
                <div class='editor_buttons'>
                    <button type="submit" class="btn btn-primary" onclick="post_check()">提交</button>
                </div>
    </fieldset>


</form>

<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script> -->


{% endblock %}


{% block bottombody %}
<link href="/static/css/simplemde.min.css" rel="stylesheet">
<script src="/static/js/simplemde.min.js"></script>
<script>
    $(document).ready(function() {
        var simplemde = new SimpleMDE({
            element: $("#create-post-content")[0]
        });

        cn_obj = {
            'Bold (Ctrl-B)': '加粗 (Ctrl-B)',
            'Italic (Ctrl-I)': '斜体 (Ctrl-I)',
            'Heading (Ctrl-H)': '标题 (Ctrl-H)',
            "Quote (Ctrl-')": "引用 (Ctrl-')",
            'Generic List (Ctrl-L)': '列表 (Ctrl-L)',
            'Numbered List (Ctrl-Alt-L)': '有序列表 (Ctrl-Alt-L)',
            'Create Link (Ctrl-K)': '链接 (Ctrl-K)',
            'Insert Image (Ctrl-Alt-I)': '插入图片 (Ctrl-Alt-I)',
            'Toggle Preview (Ctrl-P)': '预览 (Ctrl-P)',
            'Toggle Side by Side (F9)': '分栏 (F9)',
            'Toggle Fullscreen (F11)': '全屏 (F11)',
            'Markdown Guide': '手册',

        }
        obj = $('.editor-toolbar a')
        for (i = 0; i < obj.length; i++) {
            obj[i].title = Object.values(cn_obj)[i]
        }

    })
</script>
{% endblock %}

app/templates/post/detail.html
{% extends "base.html" %}

{% block head %}
{{ super() }}

<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
{% endblock %}


{% block content %}

{% include "post/sidebar.html" %}

<div class="post-detail">

    <div class='detail-header'>
        <h1 class="header-title">
            {{ post.title }}
        </h1>


        <div class="header-info">

            <p class="header-basic-p">
                <span class="header-basic-p-span">板块</span>
                <a class="header-basic-p-a">{{ board.name }}</a>
            </p>

            <p class="header-basic-p">
                <span class="header-basic-p-span">楼主</span>
                <a class="header-basic-p-a"> {{ author.username or 'Mr.R'}}</a>
            </p>

            <p class="header-basic-p">
                <span class="header-basic-p-span">热度</span>
                <a class="header-basic-p-a">{{ post.views }}</a>
            </p>
        </div>

        <p class="header-basic-date">
            时间:{{ date }}
        </p>
    </div>
    <hr>


    <div class='detail-content'>
        <p id="content-md">{{ post.content }}</p>
    </div>
    <hr>


    <div class="detail-comment-show">
        <p class="header-basic-p">
            <span class="header-basic-p-span">评论</span>
            <a class="header-basic-p-a">{{ post.comments() | count }} </a>
        </p>
        {% for r in post.comments() %}
        <div class="comment-item">
            <div class='comment-info'>

                <div class='comment-user'>
                    <img class="comment-user-img"></img>
                    <a class="comment-number">
                        {{ r.user.username }}
                    </a>

                    <a class="comment-number">
                        {{ loop.index }}楼
                    </a>

                </div>


            </div>
            <div id="comment-content">
                <div class="comment-content-text">
                    {{ r.content }}
                </div>

                <p class="header-basic-date">
                    {{ r.ut }}
                </p>
            </div>

        </div>
        {% endfor %}
    </div>

    <div class="detail-comment-edit">
        <form action="{{ url_for('comment.add') }}" method="post">
            <input type="hidden" name="post_id" value="{{ post.id }}">
            <textarea id="comment-edit-content" class="form-control" name="content" required></textarea>
            <button class="btn">添加回复</button>
            <!-- <span id="comment-add-md" class="btn btn-info">Markdown模式</span> -->
            <span id="comment-edit-reset" class="btn  btn-warning">重置</span>
        </form>
    </div>


    {% endblock %}



    {% block bottombody %}
    <script>
        document.getElementById('content-md').innerHTML = marked($('#content-md').text())
        $('#comment-edit-reset').click(function(event) {
            $('#comment-edit-content').val("")

        })
    </script>

    {% endblock %}

app/templates/post/post_index.html
{% extends "base.html" %}

{% block content %}

{% include "post/sidebar.html" %}
<div class="post-board">
    <!-- <div class="post-board-img">

    </div> -->


    <!-- 笨方法 先用着 -->
    {% if board_name == '' %}
    <a href="/post" class="post-tab current-tab">
        <span class="btn btn-secondary">全部</span>
    </a>
    {% else %}
    <a href="/post" class="post-tab ">
        <span class="btn btn-secondary">全部</span>
    </a>
    {% endif %}


    {% for b in bs %}

    {% if b.title == board_name %}
    <a href="/post?board_name={{ b.title }}" class="post-tab current-tab">
        <span class="btn btn-secondary">{{ b.name }}</span>
    </a>
    {% else %}
    <a href="/post?board_name={{ b.title }}" class="post-tab">
        <span class="btn btn-secondary">{{ b.name }}</span>
    </a>
    {% endif %}
    {% endfor %}
</div>

<hr>

<div class="post-content">

    <div class="content-items">

        {% for post in posts %}

        <div class="post-item">
            <a class="post-i-title" href="{{ url_for('post.detail', id=post.id) }}">
                {{ post.title }}
            </a>
            <span class="post-i-info">{{ post.comments() | count }}评 / {{ post.views }}阅</span>

            <span class="post-i-button">
                {% if user.id == post.user_id or user.id == 1 %}
                <a class="" href="{{ url_for('post.delete', id=post.id, token=token) }}">
                    删除
                </a>
                {% endif %}
            </span>
        </div>
        {% endfor %}
    </div>


</div>


<div class="pagination">
    <ul class="pagination">
        <li{% if not pagination.has_prev %} class="disabled" {% endif %}>
            <a href="{% if pagination.has_prev %}{{ url_for('post.index', page=pagination.page-1, board_name=board_name)}}{% else %}#{% endif %}">&laquo;
            </a>
            </li>

            {% for p in pagination.iter_pages() %}
            {% if p %}

            <!-- 当前页 -->
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for('post.index', page = p,  board_name=board_name) }}">{{ p}}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for('post.index', page = p,  board_name=board_name) }}">{{ p }}</a>
            </li>
            {% endif %}

            {% else %}
            <li class="disabled"><a href="#">&hellip;</a>
            </li>
            {% endif %}
            {% endfor %}

            <li{% if not pagination.has_next %} class="disabled" {% endif %}>
                <a href="{% if pagination.has_next %}{{ url_for('post.index', page=pagination.page+1, board_name=board_name) }}{% else %}#{% endif %}">
                    &raquo;
                </a>
                </li>
    </ul>
</div>

{% endblock %}

app/templates/post/sidebar.html
<div class="post-sidebar">

    <div class="sidebar-top">
        <a href="/post/new">
            <span class="btn btn-info">发布话题</span>
        </a>

        <a href="/post/random">
            <span class="btn btn-success">试试手气</span>
        </a>
    </div>
    <hr>
    <div class="sidebar-bottom">
        <header>
            今日板
        </header>

        <article>
            <br>

            <p>你需要跑得越来越快，才能保持原地不动</p>
            <p>———《爱丽丝梦游仙境》</p>

        </article>
    </div>


</div>

app/templates/post/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="/">
                    <span class="logo-1">T<span class="logo-2">Sure</span></span>
                </a>
                <form id="search_form" class="navbar-search" action="/search">
                    <input type="text" id="q" name="q" class="search-query span3" value="" autocomplete="off">
                </form>
                <ul class="nav pull-right">
                    <li><a href="/topic">首页</a></li>
                    <li><a href="/board/admin">板块</a></li>
                    <li><a href="https://whochat.essayer.cc/">发现</a></li>
                    {% if current_user %}
                        <li><a href="/logout">退出登陆</a></li>

                    {% else %}
                        <li><a href="/signup">注册</a></li>
                        <li><a href="/signin">登录</a></li>
                    {% endif %}


                </ul>
                <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
            </div>

        </div>
    </div>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                              <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                  <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                              </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>